# Generated by Django 4.0.3 on 2022-06-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0003_rename_telephoone1_name_company_telephone1_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit', 'Carte de crédit'), ('int', 'Interac'), ('trans', 'Transfert bancaire'), ('compt', 'Comptant'), ('other', 'Autre')], max_length=255, null=True),
        ),
    ]
