# Generated by Django 4.0.3 on 2022-06-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0006_realestate_address_city_realestate_address_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
