# Generated by Django 4.0.3 on 2022-06-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0008_alter_language_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='latitude',
            field=models.CharField(blank=True, default='', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='longitude',
            field=models.CharField(blank=True, default='', max_length=70, null=True),
        ),
    ]
