# Generated by Django 4.0.3 on 2022-06-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0009_company_latitude_company_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='draw_shape',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
