# Generated by Django 4.0.3 on 2022-06-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0010_realestate_draw_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='length_letters',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='width_letters',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
