# Generated by Django 4.0.3 on 2022-06-14 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0011_realestate_length_letters_realestate_width_letters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realestate',
            old_name='price_monyh',
            new_name='price_month',
        ),
    ]
