# Generated by Django 4.0.3 on 2022-06-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0012_rename_price_monyh_realestate_price_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='SMSW_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='door_entrence',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='p',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='realestate',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='type',
            field=models.CharField(choices=[('room', 'Room'), ('whareouse', 'Wharehouse'), ('building', 'Building'), ('house', 'House'), ('self_storage', 'Self storage'), ('local', 'Local')], max_length=40),
        ),
    ]
