# Generated by Django 4.0.3 on 2022-06-14 11:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0014_alter_realestate_created_alter_realestate_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
