# Generated by Django 4.0.3 on 2022-06-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0018_alter_realestate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='price_month',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='price_year',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
