# Generated by Django 4.0.3 on 2022-07-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0019_alter_realestate_price_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('salutation', models.CharField(blank=True, max_length=15, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('compagnie', models.CharField(blank=True, max_length=150, null=True)),
                ('fullname', models.CharField(blank=True, default='salut', max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone2', models.CharField(blank=True, max_length=20, null=True)),
                ('telephonedetails', models.CharField(blank=True, max_length=40, null=True)),
                ('telephone2details', models.CharField(blank=True, max_length=40, null=True)),
                ('website', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('email2', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('typecontact', models.CharField(blank=True, max_length=50, null=True)),
                ('address_full', models.CharField(blank=True, max_length=255, null=True)),
                ('address_street', models.CharField(blank=True, max_length=100, null=True)),
                ('address_city', models.CharField(blank=True, max_length=50, null=True)),
                ('address_province', models.CharField(blank=True, max_length=50, null=True)),
                ('address_country', models.CharField(blank=True, max_length=100, null=True)),
                ('address_postalcode', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('pucenum', models.CharField(blank=True, max_length=50, null=True)),
                ('facturesuivi', models.BooleanField(blank=True, default=False, null=True)),
                ('facturesuivi2', models.BooleanField(blank=True, default=False, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
